name:                aoc2018
version:             0.1.0.0
github:              "jeeger/aoc2018"
license:             BSD3
author:              "Jan Seeger"
maintainer:          "jan.seeger@thenybble.de"
copyright:           "2018 Jan Seeger"

# extra-source-files:
# - README.md
# - ChangeLog.md
# 
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeeger/aoc2018#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- containers
- attoparsec
- text
- pretty-simple

library:
  source-dirs: .
